<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GestionEmpleados.DAL\GestionEmpleados.DAL.csproj" />
    <ProjectReference Include="..\GestionEmpleados.Entities\GestionEmpleados.Entities.csproj" />
  </ItemGroup>

</Project>
